# Generated by Django 2.2.12 on 2020-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20201214_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='姓名')),
                ('age', models.IntegerField(default=1, verbose_name='年纪')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
            ],
            options={
                'db_table': 'Author',
            },
        ),
    ]
