# Generated by Django 2.2.12 on 2020-12-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='书名')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='定价')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='零售价')),
                ('pub', models.CharField(max_length=30, verbose_name='出版社')),
            ],
        ),
    ]
